# Generated by Django 5.2.8 on 2025-11-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0004_bmicalculator_cartitem_trainingschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('training', 'Training'), ('facility', 'Facility'), ('events', 'Events'), ('team', 'Team')], max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="IT'S ALL ABOUT WHAT YOU CAN ACHIEVE", max_length=200)),
                ('subtitle', models.TextField(default='Empower yourself to make the changes you need to make. Elite boxing training for champions.')),
                ('hero_button_1_text', models.CharField(default='Start Training', max_length=50)),
                ('hero_button_1_link', models.CharField(default='/training-schedule', max_length=100)),
                ('hero_button_2_text', models.CharField(default='Learn More', max_length=50)),
                ('hero_button_2_link', models.CharField(default='/about', max_length=100)),
            ],
        ),
    ]
