# Generated by Django 5.2.8 on 2025-11-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0005_galleryimage_homepagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='CHAMPIONSHIP', max_length=200)),
                ('subtitle', models.CharField(default='MEMBERSHIP PLANS', max_length=200)),
                ('description', models.TextField(default='Choose the perfect training program to unleash your potential and join our championship legacy')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('beginner', 'Beginner'), ('pro', 'Pro Fighter'), ('elite', 'Elite'), ('custom', 'Custom')], default='beginner', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(help_text='e.g., 1 Month, 3 Months, 1 Year', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(help_text='List features separated by commas')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular plan')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
