# Generated by Django 5.2.8 on 2025-11-14 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0006_membershippagecontent_membershipplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
