# Generated by Django 5.2.8 on 2025-11-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0007_membershipplan_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='membershippagecontent',
            name='hot_sale_description',
            field=models.TextField(default="Special discounted plans for a limited time. Don't miss this opportunity!"),
        ),
        migrations.AddField(
            model_name='membershippagecontent',
            name='hot_sale_title',
            field=models.CharField(default='HOT SALE - LIMITED TIME OFFER', max_length=200),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='custom_duration',
            field=models.CharField(blank=True, help_text='For custom duration only', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_hot_sale',
            field=models.BooleanField(default=False, help_text='Mark as hot sale plan'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration',
            field=models.CharField(choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('12_months', '12 Months'), ('custom', 'Custom Duration')], default='1_month', max_length=20),
        ),
    ]
