# Generated by Django 5.2.8 on 2025-11-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0008_remove_membershipplan_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage for hot sale', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='hot_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special price for hot sale', max_digits=10, null=True),
        ),
    ]
